# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-datadog-private-location-ecs
  description: "This component is responsible for creating a datadog private location and deploying it to ECS (EC2 / Fargate)"
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
